filebeat.inputs:
  - type: container
    format: docker
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
      - add_docker_metadata: ~
      - drop_event:
          when:
            not:
              equals:
                container.labels.filebeat_enable: "true"

logging.metrics.enabled: false

output.logstash:
  hosts: "logstash:5044"