filebeat.inputs:
  - type: container
    format: docker
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      - drop_event:
          when.not.equals:
            container.labels.ship_logs_with_filebeat: "true"
      - decode_json_fields:
          when.equals:
            container.labels.decode_log_as_json_object: "true"
          fields: ["message"]
          target: ""
          overwrite_keys: true

logging.metrics.enabled: false

output.logstash:
  hosts: "logstash:5044"