version: "3.1"
services:

  elasticsearch:
    image: elasticsearch:7.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  kibana:
    image: kibana:7.1.1
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.1.1
    ports:
      - '25826:25826'
      - '5000:5000'
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/config:/usr/share/logstash/config:ro
      - ./log:/var/log:ro