version: "3.5"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      # Persistence data
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: on-failure

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.1.1
    depends_on:
      - elasticsearch
    volumes:
      # Configuration file
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      # Docker logs
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Additional information about containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persistence data
      - ./filebeat/data:/usr/share/filebeat/data:rw

    user: root # Allow access the log files and docker.sock
    restart: on-failure

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    ports:
      - "25826:25826"
      - "5044:5044"
    depends_on:
      - elasticsearch
    volumes:
      # Pipeline configuration
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

  review-service:
    image: cassiomolin/review-service:latest
    ports:
      - "8002:8002"

  movie-service:
    image: cassiomolin/movie-service:latest
    ports:
      - "8001:8001"