filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.json
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true
      message_key: message

output.logstash:
  hosts: '${LOGSTASH_HOSTS:logstash:5044}'
